name: Android Build & Deploy

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal_patch"
        type: choice
        options:
          - internal_patch
          - internal_minor
          - internal_major
          - promote_internal_to_beta
          - promote_beta_to_production
          - promote_internal_to_production
          - production_patch
          - production_minor
          - production_major
          - firebase_dist_patch
          - firebase_dist_minor
          - firebase_dist_major
      firebase_groups:
        description: "Firebase Distribution groups (comma-separated)"
        required: false
        default: "testers"
        type: string

jobs:
  release-android:
    uses: ./.github/workflows/release-app.yml
    with:
      platform: android
      lane: ${{ github.event.inputs.lane }}
      firebase_groups: ${{ github.event.inputs.firebase_groups }}
    secrets: inherit

  bump-version:
    needs: release-android
    if: ${{ github.event.inputs.lane != 'promote_internal_to_beta' && github.event.inputs.lane != 'promote_beta_to_production' && github.event.inputs.lane != 'promote_internal_to_production' }}
    uses: ./.github/workflows/bump-version.yml
    with:
      lane: ${{ github.event.inputs.lane }}
    secrets: inherit
